version: "3.9"

services:
  pgadmin:
    image: dpage/pgadmin4:latest
    platform: ${PLATFORM:-linux/amd64}
    ports:
      - "5050:80"    # Web interface port
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL:-admin@admin.com}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD:-admin}
      - PGADMIN_CONFIG_SERVER_MODE=False
    volumes:
      - ./pgadmin/data:/var/lib/pgadmin
    depends_on:
      - postgres 