version: "3.9"

services:
  wildfly-init:
    image: quay.io/wildfly/wildfly:${WILDFLY_VERSION:-latest}
    platform: ${PLATFORM:-linux/amd64}
    volumes:
      - ./wildfly/domain/configuration:/opt/jboss/wildfly/domain/configuration:rw
      - ./wildfly/standalone/configuration:/opt/jboss/wildfly/standalone/configuration:rw
    environment:
      - JBOSS_HOME=/opt/jboss/wildfly
      - JBOSS_MODE=${WILDFLY_MODE:-domain}
      - WILDFLY_ADMIN_USER=${WILDFLY_ADMIN_USER:-admin}
      - WILDFLY_ADMIN_PASSWORD=${WILDFLY_ADMIN_PASSWORD:-admin123}
    command: >
      bash -c "
        if [ \"$JBOSS_MODE\" = \"domain\" ]; then
          /opt/jboss/wildfly/bin/add-user.sh -m -u ${WILDFLY_ADMIN_USER} -p ${WILDFLY_ADMIN_PASSWORD} --silent;
        else
          /opt/jboss/wildfly/bin/add-user.sh -u ${WILDFLY_ADMIN_USER} -p ${WILDFLY_ADMIN_PASSWORD} --silent;
        fi
      "

  wildfly:
    image: quay.io/wildfly/wildfly:${WILDFLY_VERSION:-latest}
    platform: ${PLATFORM:-linux/amd64}
    depends_on:
      - wildfly-init
    ports:
      - "8080:8080"    # HTTP port
      - "9990:9990"    # Management port
      - "8787:8787"    # Debug port
      - "8788:8788"    # Server group 'other' port
    volumes:
      - ./wildfly/domain/configuration:/opt/jboss/wildfly/domain/configuration:rw
      - ./wildfly/standalone/configuration:/opt/jboss/wildfly/standalone/configuration:rw
      - ./wildfly/modules:/opt/jboss/wildfly/modules:rw
    environment:
      - JBOSS_HOME=/opt/jboss/wildfly
      - JBOSS_MODE=${WILDFLY_MODE:-domain}
      - JBOSS_DOMAIN_CONFIG=${WILDFLY_DOMAIN_CONFIG:-domain.xml}
      - JBOSS_HOST_CONFIG=${WILDFLY_HOST_CONFIG:-host.xml}
      - JBOSS_STANDALONE_CONFIG=${WILDFLY_STANDALONE_CONFIG:-standalone.xml}
    command: >
      bash -c "
        if [ \"$JBOSS_MODE\" = \"domain\" ]; then
          /opt/jboss/wildfly/bin/domain.sh -b 0.0.0.0 -bmanagement 0.0.0.0;
        else
          /opt/jboss/wildfly/bin/standalone.sh -b 0.0.0.0 -bmanagement 0.0.0.0;
        fi
      "
